"""add unique constraint to non_tariff_measures

Revision ID: 362469881239
Revises: b1c2d3e4f5a6
Create Date: 2026-04-09 16:18:17.429313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '362469881239'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('non_tariff_measures', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_non_tariff_measures_code_type_act', ['commodity_code', 'measure_type', 'regulatory_act'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('non_tariff_measures', schema=None) as batch_op:
        batch_op.drop_constraint('uq_non_tariff_measures_code_type_act', type_='unique')

    # ### end Alembic commands ###
