#!/usr/bin/env python3
"""Render PR body for cursor-task automation."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


def _changed_files_since_main() -> list[str]:
    try:
        out = subprocess.check_output(
            ["git", "diff", "--name-only", "main...HEAD"],
            text=True,
            stderr=subprocess.DEVNULL,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        try:
            out = subprocess.check_output(
                ["git", "diff", "--cached", "--name-only"],
                text=True,
                stderr=subprocess.DEVNULL,
            )
        except (subprocess.CalledProcessError, FileNotFoundError):
            return []
    return [line.strip() for line in out.splitlines() if line.strip()]


def render_pr_body(
    ctx: dict,
    *,
    workflow_run_url: str,
    test_status: str,
    agent_note: str,
) -> str:
    n = int(ctx["number"])
    issue_url = str(ctx.get("html_url") or f"https://github.com/issues/{n}")
    changed = _changed_files_since_main()
    if changed:
        files_block = "\n".join(f"- `{path}`" for path in changed)
    else:
        files_block = "- _(no file list available — see commit diff)_"

    return f"""## Summary

Automated implementation for **Cursor Task** issue #{n} via GitHub Actions + Cursor CLI.

> This PR was generated by automation. Human review (Codex + Ivan) is required before merge.

## Source issue

- Issue: #{n}
- Link: {issue_url}

## Workflow run

- Run: {workflow_run_url}
- Agent note: {agent_note}

## Changed files

{files_block}

## Tests / logs

{test_status}

## Risks / limitations

- Prompt-injection and scope risks are mitigated in workflow (trusted actors, staged denylist, no git credentials during agent step) but **review is still mandatory**.
- Verify feature flags remain default OFF unless the issue explicitly enabled them.
- Confirm no broker / missing-check semantic changes unless requested in the issue.

## Follow-up

- Codex review per `docs/ai-workflow/CODEX_REVIEW_CHECKLIST.md`
- Ivan merge when `ready-for-ivan-review`

Relates to #{n}
""".strip()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("issue_context", help="Path to issue-context.json")
    parser.add_argument(
        "--workflow-run-url",
        default="",
        help="GitHub Actions workflow run URL",
    )
    parser.add_argument(
        "--test-status",
        default="See workflow run logs for commands executed by Cursor agent.",
    )
    parser.add_argument(
        "--agent-note",
        default="Cursor agent run in CI (see workflow logs).",
    )
    args = parser.parse_args()

    path = Path(args.issue_context)
    ctx = json.loads(path.read_text(encoding="utf-8"))
    print(
        render_pr_body(
            ctx,
            workflow_run_url=args.workflow_run_url,
            test_status=args.test_status,
            agent_note=args.agent_note,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
