"""Tests for cursor-task PR body renderer."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from render_cursor_task_pr_body import render_pr_body  # noqa: E402

RENDER_SCRIPT = Path(__file__).resolve().parent / "render_cursor_task_pr_body.py"


def test_render_pr_body_includes_required_sections() -> None:
    body = render_pr_body(
        {"number": 7, "title": "Test", "html_url": "https://github.com/o/r/issues/7"},
        workflow_run_url="https://github.com/o/r/actions/runs/99",
        test_status="pytest: 10 passed",
        agent_note="agent ok",
    )
    assert "https://github.com/o/r/issues/7" in body
    assert "https://github.com/o/r/actions/runs/99" in body
    assert "pytest: 10 passed" in body
    assert "generated by automation" in body.lower()
    assert "Risks / limitations" in body
    assert "Relates to #7" in body


def test_render_script_cli(tmp_path: Path) -> None:
    ctx_path = tmp_path / "issue-context.json"
    ctx_path.write_text(
        json.dumps(
            {
                "number": 3,
                "title": "Task",
                "html_url": "https://github.com/o/r/issues/3",
            }
        ),
        encoding="utf-8",
    )
    out = subprocess.check_output(
        [
            sys.executable,
            str(RENDER_SCRIPT),
            str(ctx_path),
            "--workflow-run-url",
            "https://github.com/o/r/actions/runs/1",
            "--test-status",
            "logs ok",
        ],
        text=True,
    )
    assert "Changed files" in out
    assert "https://github.com/o/r/actions/runs/1" in out
